apiVersion: v1
data:
  oauth2-proxy.cfg: |-
    # Provider config
    provider="keycloak"
    login_url="https://keycloak.tukktukk.com/realms/Test/protocol/openid-connect/auth"
    redeem_url="https://keycloak.tukktukk.com/realms/Test/protocol/openid-connect/token"
    validate_url="https://keycloak.tukktukk.com/realms/Test/protocol/openid-connect/userinfo"
    profile_url="https://keycloak.tukktukk.com/realms/Test/protocol/openid-connect/userinfo"
    # Client config
    client_id="argocd"
    client_secret="39sABWz3KSZK4CWk8yKCHViqbh7WPVHj"
    cookie_secret="ZzBkN000Wm0pQkVkKUhzMk5YPntQRUw_ME1oMTZZTy0="
    cookie_secure="true"
    # Upstream config
    email_domains=["*"]
    oidc_issuer_url="https://keycloak.tukktukk.com/realms/Test"
    cookie_domains=["argocd.tukktukk.com"]
    scope="openid"
    whitelist_domains=[".argocd.tukktukk.com:*"]
    # Redis session store config
    session_store_type="redis"
    redis_connection_url="redis://redis-service.argocd:6379"
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: argocd