apiVersion: v1
kind: Service
metadata:
  labels:
    mysql.oracle.com/cluster: dev-db-cluster
    tier: mysql
  name: dev-db-cluster-nlb
  namespace: dev-db-cluster
  ownerReferences:
  - apiVersion: mysql.oracle.com/v2
    blockOwnerDeletion: true
    controller: true
    kind: InnoDBCluster
    name: dev-db-cluster
    uid: 56881413-87eb-4f5e-af77-965eca136b2c
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 6446
  - name: mysqlx
    port: 33060
    protocol: TCP
    targetPort: 6448
  - name: mysql-alternate
    port: 6446
    protocol: TCP
    targetPort: 6446
  - name: mysqlx-alternate
    port: 6448
    protocol: TCP
    targetPort: 6448
  - name: mysql-ro
    port: 6447
    protocol: TCP
    targetPort: 6447
  - name: mysqlx-ro
    port: 6449
    protocol: TCP
    targetPort: 6449
  - name: mysql-rw-split
    port: 6450
    protocol: TCP
    targetPort: 6450
  - name: router-rest
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    component: mysqlrouter
    mysql.oracle.com/cluster: dev-db-cluster
    tier: mysql
  sessionAffinity: None
